import fs from 'node:fs/promises';
const cinematic='Cinematic editorial photography with believable materials, controlled warm practical lighting and fine film grain. Forest green #2F4936, cream #F6F2EE, burnt orange #C96E43 and brass gold #D9AB4D. Art direction for a premium camp-themed higher-education marketing campaign.';
const entries=[
 ['forest-arrival','cinematic','A secluded forest clearing at blue hour, a beautiful dark green canvas A-frame tent on the right, warm lantern light spilling onto pine needles, a quiet path entering from the foreground, tall pines layered in mist. Wide 16:9 view, left half subdued with room for live typography. No people.','Homepage, traditional, quiz, story form'],
 ['campfire-circle','cinematic','An intimate circle of four empty canvas camp chairs around a low stone campfire, beside a still alpine lake, dusk, tall pines and smoke, amber reflections. Camera low and wide 16:9, fire slightly right of center, natural asymmetry and generous atmospheric depth.','Campfire, chairs, story chapter'],
 ['camp-store','cinematic','A beautifully curated outdoor camp supply hut, open dark-green doors, cream canvas tote, plain orange cap, unbranded green enamel mug and stainless bottle arranged on weathered cedar shelves, brass lantern. Wide 3:2 lifestyle product photograph, no shop lettering.','Offer and store details'],
 ['store-pass','cinematic','An unprinted cream heavyweight paper camp ticket on a dark green tabletop, orange cloth ribbon and small brass eyelet, tactile deckled fibers, blank large center for live HTML copy. Close overhead still life, 3:2 landscape, no stamps or lettering.','Claim panel'],
 ['prize-capsule','cinematic','One beautiful round collectible prize capsule, glossy transparent amber upper hemisphere and solid forest green lower hemisphere with a brass equatorial seam. Isolated on warm cream seamless background, premium macro product lighting, square composition. No mark or lettering.','Prize reveal and social detail'],
 ['forest-werewolf','cinematic','A cinematic folklore werewolf standing between huge pines beside a misty forest path at night, shaggy dark fur rimlit by moonlight, small amber eyes, threatening but non-graphic, distant orange lantern light. Wide 16:9 composition, creature in right third. No blood or gore.','Opt-in flashlight encounter'],
 ['demon-bonfire','cinematic','A fantastical enormous camp bonfire beneath towering pines at midnight, several impish horned shadow creatures dancing in a ring at a safe distance, embers spiraling upward, dark green shadows and rich orange fire. Epic wide 16:9 view, non-graphic folklore cinema, no gore.','Opt-in chaos experiment'],
 ['mountain-dawn','cinematic','Dramatic layered mountain ridges above a pine valley at first light, warm cream dawn sky, muted golden sun on granite, dark green foreground with a visible winding trail. Wide 16:9 expansive outdoor editorial landscape.','Bouldering, day mode, story chapter'],
 ['machine-surface','cinematic','A flat straight-on decorative enamel panel for the inside back wall of a luxury camp claw machine. Subtle engraved contour lines, restrained stylized pine motifs near lower corners, dark forest-green enamel with soft aged brass detailing. Entire image is the material panel, square, even studio light, no perspective, no machine, no text.','3D cabinet interior texture'],
 ['arcade-interior','field-guide','A hand-painted woodland diorama background for a front-facing illustrated claw arcade: layered evergreen trees, tiny stars, distant ridges, golden lantern glow low at center. Dark green, cream, burnt orange and ochre, rich gouache and printed paper texture. Square, flat front view, empty central foreground for live game objects, no machine frame or capsules.','2.5D separate interior layer'],
 ['arcade-frame','field-guide','A decorative front-facing arcade cabinet outer panel surface, rich forest-green painted enamel with hand-painted cream and ochre botanical flourishes at outer corners and restrained brass screw details around the border. Flat rectangular portrait 3:4 composition, broad dark blank central field, no controls, no lettering, no claw, no capsules, no scene. Production game surface artwork.','2.5D separate cabinet layer'],
 ['field-campsite','field-guide','An extraordinary illustrated field-guide plate of a camp in pine woods: burnt orange A-frame tent, tiny lantern, stream, moon, layered forest and winding cream footpath. Hand-cut shapes and fine woodcut hatching, tactile gouache on warm cream paper. Sophisticated limited palette of forest green, rust, ochre and cream. Wide 3:2 composition, no lettering, not a map UI.','Illustrated homepage hero'],
 ['field-gear','field-guide','A carefully arranged illustrated field-guide still life of an enamel camp mug, rolled canvas blanket, compass and pine sprig. Hand-cut shapes, delicate woodcut hatching, warm cream paper texture. Forest green, burnt orange and ochre palette. Square composition with generous breathing room. No readable numbers or text.','Illustrated offer section'],
 ['surreal-camp','surreal','A surreal high-end campaign image: an immense cream canvas tent floating on a small island of pine forest above a green alpine lake, a perfect orange sun suspended inside its entrance, a brass ladder impossibly reaching down to the water. Dreamlike tactile 3D sculpture and editorial art photography, green and cream world with burnt orange accents. Wide 16:9 image, dramatic precise composition, no people or lettering.','Surreal homepage hero'],
 ['surreal-prize','surreal','A surreal collectible sculpture: an oversized glossy amber prize capsule split open with a tiny pine forest and a cream canvas tent growing inside, balanced on a forest green stone plinth. Burnt orange backdrop, precise studio shadow, premium tactile art-object photograph, square. No logos or text.','Surreal claim section'],
 ['surreal-forest','surreal','An impossible forest corridor of dark green pine trees whose trunks curve into a monumental circular portal, a warm cream moon and small orange tent seen through it, reflective still water beneath. Surreal practical miniature photography with fine tactile detail, wide 16:9, restrained palette. No lettering.','Surreal secondary panel and preview']
];
const assets=entries.map(([slug,lane,subject,consumer])=>({slug,lane,consumer,target:`${lane==='field-guide'&&!slug.startsWith('arcade')?'../field-guide':lane==='surreal'?'../surreal':'.'}/assets/generated/${slug}.webp`,status:'pending',prompt:`Use case: ${lane==='field-guide'?'illustration-story':'stylized-concept'}. Asset type: production web campaign artwork. ${lane==='cinematic'?cinematic:''} Primary request: ${subject} Create an entirely new image from this text description only. No input image references. No watermark, no logos, no readable text, no browser chrome, no website layout, no fake UI. Carefully art-directed, production-quality detail.`}));
await fs.mkdir('artwork',{recursive:true});await fs.writeFile('artwork/manifest.json',JSON.stringify({generation:'Built-in image generator; text-only; originals reviewed but never supplied as input.',assets},null,2));
await fs.writeFile('artwork/REVIEW.md','# Original artwork review\n\nReviewed original booth mockup, existing generated booth hero, claw machine raster, bonfire raster and campfire/creature SVG source. Motifs: timber frames, pine silhouettes, amber lantern light, forest green enamel, cream type, orange accents, glossy prize capsules. The new direction moves from a trade-show booth recreation to an outdoor editorial campsite, and builds the machine itself as interactive geometry. No original campaign artwork is copied. Official logo and approved type/color tokens are retained.\n\nThe illustrated direction uses woodcut/gouache textures; the surreal direction uses impossible practical-miniature compositions. Each image request is distinct and uses text only.\n');
