'use strict';
(() => {
const $=id=>document.getElementById(id), cv=$('game'), ctx=cv.getContext('2d',{alpha:false});
const W=480,H=720,TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const STORE='nonrocker-overdrive-v1', QA=new URLSearchParams(location.search).has('qa');
const stages=[
 {name:'ACID COAST',boss:'THE BOTTLE SERVICE',base:'#130e29',hot:'#e94328',cool:'#18378c',duration:52,hp:340},
 {name:'COBALT RIOT',boss:'FEEDBACK MACHINE',base:'#0b152b',hot:'#1533cb',cool:'#953f9e',duration:58,hp:470},
 {name:'MOLTEN FREQUENCY',boss:'LAST CALL / NRK–666',base:'#211020',hot:'#ff6f12',cool:'#ad224a',duration:64,hp:640}
];
let saved={scores:[],sound:false,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,difficulty:'normal'};
try { const raw=JSON.parse(localStorage.getItem(STORE)||'null');if(raw&&typeof raw==='object')saved={...saved,...raw}; }catch{}
saved.scores=Array.isArray(saved.scores)?saved.scores.filter(s=>s&&Number.isFinite(s.score)&&typeof s.name==='string').slice(0,8):[];
saved.difficulty=saved.difficulty==='chill'?'chill':'normal';
let storageOK=true;
function persist(){try{localStorage.setItem(STORE,JSON.stringify(saved));}catch{storageOK=false;}}
let seed=613;function rnd(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}const rand=(a,b)=>a+rnd()*(b-a);
let state='title',t=0,runTime=0,stage=0,stageTime=0,nextWave=1,wave=0,score=0,kills=0,combo=0,comboTimer=0,charge=0,drive=0,driveHit=0;
let enemies=[],shots=[],bullets=[],particles=[],drops=[],rings=[],boss=null,transition=0,noticeTimer=0,shake=0,savedRun=false,difficulty='normal',endingWin=false;
let player={x:240,y:614,hp:3,power:1,inv:0,fire:0}, keys=new Set(),pointer=null,ready=false,last=0,acc=0,hudClock=0;
let totalSpawned=0,escaped=0,qaGod=false,qaManual=false;
// Custom atlas bounds accommodate the generated sprites' different silhouettes.
const atlas=new Image(),terrain=new Image();let atlasReady=false,terrainReady=false;
function assetsReady(){ready=atlasReady&&terrainReady;if(ready){$('start-btn').disabled=false;$('start-btn').textContent='START FLIGHT →';}}
atlas.src='assets/nonrocker-atlas.png';terrain.src='assets/signal-terrain.png';
const rects={jet:[8,32,396,510],soju:[447,34,369,507],vinyl:[850,61,395,482],kazoo:[4,575,324,648],boss:[335,565,563,654],moth:[897,620,350,568]};
const sprites={};
atlas.onload=()=>{for(const [name,r]of Object.entries(rects)){const c=document.createElement('canvas');c.width=r[2];c.height=r[3];c.getContext('2d').drawImage(atlas,...r,0,0,r[2],r[3]);sprites[name]=c;}atlasReady=true;assetsReady();};
atlas.onerror=()=>{$('start-btn').textContent='ART FAILED TO LOAD — RELOAD';$('flight-status').textContent='CHECK LOCAL ASSET FILE';};
terrain.onload=()=>{terrainReady=true;assetsReady();};terrain.onerror=atlas.onerror;

// All audio is synthesized locally after a user gesture.
let audio=null,musicStep=0,musicTimer=0;
function unlockAudio(){if(!saved.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{saved.sound=false;$('sound').checked=false;}}
function tone(freq,duration=.08,type='sine',volume=.03,end=freq){if(!saved.sound||!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain(),n=audio.currentTime;o.type=type;o.frequency.setValueAtTime(freq,n);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),n+duration);g.gain.setValueAtTime(volume,n);g.gain.exponentialRampToValueAtTime(.0001,n+duration);o.connect(g);g.connect(audio.destination);o.start(n);o.stop(n+duration+.01);}
function music(dt){if(!saved.sound)return;musicTimer-=dt;if(musicTimer>0)return;musicTimer=.19;const notes=[55,55,82.41,55,65.41,55,98,73.42];tone(notes[musicStep%8]*(stage===1?1.122:1),.16,'triangle',.045);if(musicStep%4===0)tone(140,.12,'sine',.08,35);if(musicStep%2===1)tone(2600,.035,'square',.006,1300);if(musicStep%8===6)tone(330,.12,'sine',.02,660);musicStep++;}
function sprite(name,x,y,w,h,angle=0,alpha=1){if(!sprites[name])return;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.globalAlpha=alpha;ctx.drawImage(sprites[name],-w/2,-h/2,w,h);ctx.restore();}
function puff(x,y,color,count=12,speed=110){for(let i=0;i<count&&particles.length<240;i++){const a=rand(0,TAU),v=rand(speed*.2,speed);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rand(.2,.65),max:.65,r:rand(1,4),color});}}
function ring(x,y,color,r=8){if(rings.length<24)rings.push({x,y,r,life:.55,color});}
function notify(s,duration=2.1){$('notice').textContent=s;$('notice').classList.add('show');noticeTimer=duration;}
function screen(id){for(const s of ['title-screen','pause-screen','result-screen'])$(s).hidden=s!==id;}
function updateScores(){const best=Math.max(0,...saved.scores.map(s=>s.score));$('best-score').textContent=String(best).padStart(6,'0');$('score-list').replaceChildren();saved.scores.slice(0,5).forEach((s,i)=>{const li=document.createElement('li');li.append(`${String(s.name).slice(0,3)} / ${s.mode==='chill'?'CHILL':'ARCADE'}`);const n=document.createElement('span');n.textContent=String(s.score).padStart(6,'0');li.append(n);$('score-list').append(li);});}
function resetStage(){stageTime=0;nextWave=1;wave=0;enemies=[];shots=[];bullets=[];drops=[];boss=null;transition=0;player.x=W/2;player.y=610;player.inv=2;notify(`TRANSMISSION 0${stage+1}\n${stages[stage].name}`,2.7);}
function start(){if(!ready)return;seed=613;state='playing';runTime=0;stage=0;score=0;kills=0;combo=0;charge=30;drive=0;comboTimer=0;totalSpawned=0;escaped=0;particles=[];rings=[];savedRun=false;endingWin=false;difficulty=saved.difficulty;player={x:240,y:614,hp:3,power:1,inv:2,fire:0};keys.clear();pointer=null;resetStage();screen(null);$('hud').hidden=false;$('pause-btn').disabled=false;$('save-btn').disabled=false;$('save-btn').textContent='SAVE LOCAL SCORE';unlockAudio();cv.focus({preventScroll:true});hud();}
function title(){state='title';keys.clear();pointer=null;screen('title-screen');$('hud').hidden=true;$('pause-btn').disabled=true;$('overdrive-btn').disabled=true;$('notice').classList.remove('show');$('flight-status').textContent='READY TO TRANSMIT';$('weapon-label').textContent='AUTO FIRE / DRAG TO STEER';$('charge-fill').style.width='0%';$('charge-label').textContent='BUILD YOUR CHARGE';$('overdrive-btn').classList.remove('ready');updateScores();}
function pause(){if(state!=='playing')return;state='paused';keys.clear();pointer=null;screen('pause-screen');$('pause-btn').disabled=true;$('overdrive-btn').disabled=true;$('flight-status').textContent='TRANSMISSION PAUSED';$('resume-btn').focus({preventScroll:true});}
function resume(){if(state!=='paused')return;state='playing';screen(null);$('pause-btn').disabled=false;last=performance.now();acc=0;unlockAudio();cv.focus({preventScroll:true});hud();}
function finish(win){state='result';endingWin=win;drive=0;pointer=null;keys.clear();screen('result-screen');$('hud').hidden=true;$('notice').classList.remove('show');$('pause-btn').disabled=true;$('overdrive-btn').disabled=true;$('result-kicker').textContent=win?'ALL TRANSMISSIONS CLEARED':'END OF TRANSMISSION';$('result-title').innerHTML=win?'NOISE<br>FOREVER.':'SIGNAL<br>LOST.';$('final-score').textContent=String(score).padStart(6,'0');$('result-detail').textContent=`${kills} TAKEDOWNS / STAGE ${stage+1} / ${difficulty.toUpperCase()}`;$('flight-status').textContent=win?'ALL STAGES CLEARED':'FLIGHT COMPLETE';updateScores();$('retry-btn').focus({preventScroll:true});tone(win?523:110,.5,'triangle',.08,win?1046:45);}
function saveScore(){if(state!=='result'||savedRun)return;const name=$('initials').value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,3)||'NRK';saved.scores.push({name,score,mode:difficulty,clear:endingWin,date:new Date().toISOString().slice(0,10)});saved.scores.sort((a,b)=>b.score-a.score);saved.scores=saved.scores.slice(0,8);persist();savedRun=true;$('save-btn').disabled=true;$('save-btn').textContent=storageOK?'SCORE SAVED ON THIS DEVICE':'SAVED FOR THIS SESSION ONLY';updateScores();}
function addScore(n){score+=Math.round(n*(1+Math.min(3,Math.floor(combo/12))));}
function takeHit(){if(player.inv>0||drive>0||qaGod)return;player.hp--;player.power=Math.max(1,player.power-1);player.inv=2.2;combo=0;shake=saved.reduced?0:9;puff(player.x,player.y,'#ff6847',20,180);ring(player.x,player.y,'#55e8ff',15);tone(100,.25,'sawtooth',.055,30);if(player.hp<=0)finish(false);}
function activateDrive(){if(state!=='playing'||charge<100||drive>0||transition>0)return;charge=0;drive=4.5;driveHit=0;bullets=[];ring(player.x,player.y,'#edff7a',50);tone(90,.7,'sawtooth',.045,600);notify('OVERDRIVE\nMAKE THE SKY LOUD',1.4);hud();}
function spawnEnemy(kind,x,y,pattern='sway'){const specs={soju:[3,44,65,24,180],vinyl:[5,58,61,26,260],kazoo:[8,45,86,27,350],moth:[3,50,65,24,220]},s=specs[kind];enemies.push({kind,x,y,baseX:x,age:0,hp:s[0]+stage*2,w:s[1],h:s[2],r:s[3],points:s[4],vy:rand(48,75)+stage*9,phase:rand(0,TAU),fire:rand(1.1,2.3),pattern,hit:0});totalSpawned++;}
function spawnWave(){const types=['soju','moth','vinyl','soju','kazoo'];const kind=types[wave%types.length],pattern=wave%3===0?'swoop':'sway',n=kind==='kazoo'?2:3+Math.min(stage,1);for(let i=0;i<n;i++)spawnEnemy(kind,65+(W-130)*(i/Math.max(1,n-1)),-60-i*32,pattern);wave++;}
function enemyShot(x,y,angle,speed=110,r=5,color='#ffbf57'){if(bullets.length>=190)return;const mul=difficulty==='chill'?.67:1;bullets.push({x,y,vx:Math.cos(angle)*speed*mul,vy:Math.sin(angle)*speed*mul,r,color});}
function aim(x,y,spread=0){return Math.atan2(player.y-y,player.x-x)+spread;}
function destroyEnemy(e){e.hp=0;combo++;comboTimer=3.5;kills++;charge=clamp(charge+4,0,100);addScore(e.points);puff(e.x,e.y,e.kind==='soju'?'#b6ff65':'#ff8962',14,140);ring(e.x,e.y,'#f5efb2');tone(100+Math.min(combo,20)*12,.07,'triangle',.023,50);drops.push({x:e.x,y:e.y,type:kills%8===0?'power':kills%13===0?'health':'record',age:0});}
function spawnBoss(){boss={x:W/2,y:-100,hp:stages[stage].hp,max:stages[stage].hp,age:0,fire:1.7,hit:0,w:stage===1?150:180,h:175};enemies=[];bullets=[];notify(`WARNING / HEAVY SIGNAL\n${stages[stage].boss}`,2.6);tone(220,.4,'triangle',.04,110);}
function beatBoss(){if(!boss)return;addScore(5000*(stage+1));kills++;puff(boss.x,boss.y,'#fcff70',55,270);ring(boss.x,boss.y,'#64eaff',60);boss=null;bullets=[];enemies=[];drops=[];shots=[];drive=0;transition=3.8;player.hp=Math.min(3,player.hp+1);player.power=Math.min(3,player.power+1);player.inv=5;charge=clamp(charge+30,0,100);notify(`TRANSMISSION 0${stage+1} COMPLETE\n+ SHIELD / + FIREPOWER`,3.6);tone(440,.3,'triangle',.05,880);}
function step(dt){t+=dt;if(state!=='playing')return;runTime+=dt;stageTime+=dt;music(dt);noticeTimer-=dt;if(noticeTimer<=0)$('notice').classList.remove('show');shake=Math.max(0,shake-dt*28);player.inv=Math.max(0,player.inv-dt);comboTimer-=dt;if(comboTimer<=0)combo=0;charge=clamp(charge+dt*1.7,0,100);drive=Math.max(0,drive-dt);
 let mx=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0),my=(keys.has('ArrowDown')||keys.has('s')?1:0)-(keys.has('ArrowUp')||keys.has('w')?1:0);const norm=Math.hypot(mx,my)||1,speed=keys.has('Shift')?115:270;player.x=clamp(player.x+mx/norm*speed*dt,25,W-25);player.y=clamp(player.y+my/norm*speed*dt,85,H-38);
 if(transition>0){transition-=dt;if(transition<=0){if(stage===2){finish(true);return;}stage++;resetStage();}}else{
 if(!boss&&stageTime<stages[stage].duration&&stageTime>=nextWave){spawnWave();nextWave+=3.2-stage*.22;}
 if(!boss&&stageTime>=stages[stage].duration)spawnBoss();
 player.fire-=dt;if(player.fire<=0){player.fire=drive>0?.12:.14;const spread=player.power===1?[0]:player.power===2?[-.08,.08]:[-.15,0,.15];for(const a of spread)shots.push({x:player.x,y:player.y-25,vx:Math.sin(a)*560,vy:-Math.cos(a)*560,r:4});if(Math.floor(runTime*7)%3===0)tone(660,.035,'triangle',.008,380);}
 }
 for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;}
 for(const e of enemies){e.age+=dt;e.hit=Math.max(0,e.hit-dt);e.y+=e.vy*dt;e.x=clamp(e.baseX+Math.sin(e.age*(e.pattern==='swoop'?1.8:1)+e.phase)*(e.pattern==='swoop'?65:28),22,W-22);e.fire-=dt;if(e.fire<=0&&e.y>35&&e.y<player.y-30){e.fire=2.1-stage*.23;const a=aim(e.x,e.y);enemyShot(e.x,e.y,a,105+stage*20);if(e.kind==='kazoo'){enemyShot(e.x,e.y,a-.22,110);enemyShot(e.x,e.y,a+.22,110);}}
  if(Math.hypot(e.x-player.x,e.y-player.y)<e.r+6)takeHit();if(state!=='playing')return;
 }
 if(boss){boss.age+=dt;boss.y=Math.min(145,boss.y+55*dt);boss.x=240+Math.sin(boss.age*.65)*120;boss.hit=Math.max(0,boss.hit-dt);boss.fire-=dt;if(boss.y>60&&boss.fire<=0){boss.fire=stage===2?.55:.8;const a=aim(boss.x,boss.y),count=stage+2;for(let i=-count;i<=count;i++)enemyShot(boss.x,boss.y+42,a+i*.17,115+stage*15,5,'#ffaf6d');if(stage>0&&Math.floor(boss.age)%4<1)for(let i=0;i<12;i++)enemyShot(boss.x,boss.y,i*TAU/12+boss.age*.3,75,4,'#fca3fc');}if(Math.hypot(boss.x-player.x,boss.y-player.y)<72)takeHit();if(state!=='playing')return;}
 for(const s of shots){if(s.dead)continue;for(const e of enemies){if(e.hp>0&&Math.hypot(s.x-e.x,s.y-e.y)<e.r+s.r){s.dead=true;e.hp--;e.hit=.07;if(e.hp<=0)destroyEnemy(e);break;}}if(!s.dead&&boss&&Math.abs(s.x-boss.x)<boss.w*.38&&Math.abs(s.y-boss.y)<boss.h*.39){s.dead=true;boss.hp--;boss.hit=.06;}}
 if(drive>0){driveHit-=dt;const beamW=55+Math.sin((4.5-drive)*.7)*30;bullets=bullets.filter(b=>Math.abs(b.x-player.x)>beamW||b.y>player.y);if(driveHit<=0){driveHit=.08;for(const e of enemies)if(e.hp>0&&e.y<player.y&&Math.abs(e.x-player.x)<beamW+e.r){e.hp-=4;e.hit=.06;if(e.hp<=0)destroyEnemy(e);}if(boss&&boss.y<player.y&&Math.abs(boss.x-player.x)<beamW+boss.w*.35){boss.hp-=5;boss.hit=.05;}}}
 if(boss&&boss.hp<=0)beatBoss();
 for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;if(Math.hypot(b.x-player.x,b.y-player.y)<b.r+5){b.dead=true;takeHit();if(state!=='playing')return;}}
 for(const d of drops){d.age+=dt;d.y+=65*dt;if(Math.hypot(d.x-player.x,d.y-player.y)<95){const a=aim(d.x,d.y);d.x+=Math.cos(a)*180*dt;d.y+=Math.sin(a)*180*dt;}if(Math.hypot(d.x-player.x,d.y-player.y)<24){d.dead=true;if(d.type==='power'){player.power=Math.min(3,player.power+1);addScore(150);notify('FIREPOWER UPGRADED',1);}else if(d.type==='health'){player.hp=Math.min(3,player.hp+1);notify('SHIELD RESTORED',1);}else{charge=clamp(charge+5,0,100);addScore(80);}tone(880,.07,'sine',.022,1320);}}
 for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;p.vx*=.98;p.vy*=.98;}for(const r of rings){r.r+=150*dt;r.life-=dt;}
 escaped+=enemies.filter(e=>e.hp>0&&e.y>H+100).length;enemies=enemies.filter(e=>e.hp>0&&e.y<H+100);shots=shots.filter(s=>!s.dead&&s.y>-30&&s.x>-10&&s.x<W+10).slice(-160);bullets=bullets.filter(b=>!b.dead&&b.y>-30&&b.y<H+30&&b.x>-30&&b.x<W+30);particles=particles.filter(p=>p.life>0);rings=rings.filter(r=>r.life>0);drops=drops.filter(d=>!d.dead&&d.y<H+25);hudClock-=dt;if(hudClock<=0){hudClock=.08;hud();}}

// Procedural scenery and typography animate independently from the vertical flight.
function background(){const st=stages[stage],clock=t,rate=saved.reduced?.22:1;ctx.fillStyle=st.base;ctx.fillRect(0,0,W,H);
 const layerT=clock*rate;
 if(terrainReady){const tw=780,offset=layerT*14%(tw*2);ctx.globalAlpha=.65;for(let i=-2;i<2;i++){ctx.save();ctx.translate(offset+i*tw,0);if(Math.abs(i)%2){ctx.translate(tw,0);ctx.scale(-1,1);}ctx.drawImage(terrain,0,0,tw,H);ctx.restore();}ctx.globalAlpha=1;}
 for(let layer=0;layer<3;layer++){ctx.globalAlpha=layer===0?.15:.08;ctx.fillStyle=layer===0?st.cool:layer===1?st.hot:'#effb51';ctx.beginPath();ctx.moveTo(0,H);for(let x=0;x<=W+12;x+=12){const yy=390+Math.sin(x*.013+layerT*.22+layer*2)*170+Math.sin(x*.033-layerT*.18+layer)*70;ctx.lineTo(x,yy);}ctx.lineTo(W,H);ctx.closePath();ctx.fill();}
 // Distorted ribbons travel from left to right, exposing the dark flight lane.
 for(let i=0;i<9;i++){const x=((i*93+layerT*(18+i%3*9))%(W+220))-110;ctx.globalAlpha=saved.reduced?.035:.075;ctx.fillStyle=i%3===0?'#d6fb39':i%3===1?st.hot:st.cool;ctx.beginPath();for(let y=-20;y<H+30;y+=16){const dx=Math.sin(y*.021+layerT*.6+i)*18+Math.sin(y*.047+i)*7;const px=x+dx;if(y===-20)ctx.moveTo(px,y);else ctx.lineTo(px,y);}for(let y=H+30;y>=-20;y-=16)ctx.lineTo(x+18+Math.sin(y*.021+layerT*.6+i)*18,y);ctx.closePath();ctx.fill();}
 ctx.globalAlpha=saved.reduced?.04:.11;ctx.fillStyle='#22f0bc';ctx.font='bold 136px monospace';const nums=['61','3','99','NRK'];for(let i=0;i<3;i++)ctx.fillText(nums[(Math.floor(layerT/5)+i)%4],W-165,((layerT*24+i*270)%1000)-90);
 const dark=ctx.createLinearGradient(0,0,W,0);dark.addColorStop(0,'#08091a88');dark.addColorStop(.35,'#08091a22');dark.addColorStop(.7,'#08091a22');dark.addColorStop(1,'#08091a99');ctx.globalAlpha=1;ctx.fillStyle=dark;ctx.fillRect(0,0,W,H);
 ctx.font='12px monospace';ctx.fillStyle='#ff342e';ctx.globalAlpha=saved.reduced?.08:.32;const offset=(layerT*30)%21;for(let i=-1;i<36;i++){const num=((i+40)*7349+Math.floor(layerT/3)*61)%99999;ctx.fillText(`${['NRK','JDH','SOJ','61/','AWV'][((i+40)%5)]}-${String(num).padStart(5,'0')}`,8,i*21+offset);}
 ctx.font='7px monospace';ctx.fillStyle='#f54ed2';ctx.globalAlpha=saved.reduced?.07:.25;for(let i=-1;i<65;i++)ctx.fillText(['NONROCKER','RECOMBINE','FORM.BOMB','NOISE.613'][(i+65)%4],424,i*12-(layerT*18%12));ctx.globalAlpha=.24;ctx.font='9px monospace';ctx.fillStyle='#4868ff';for(let i=0;i<7;i++)ctx.fillText('FORM / BOMB',i*78-(layerT*8%78),75);
 ctx.globalAlpha=.1;ctx.strokeStyle='#bcc7f4';ctx.lineWidth=1;for(let i=0;i<15;i++){let y=(i*67+layerT*95)%H;ctx.beginPath();ctx.moveTo((i*37)%W,y);ctx.lineTo((i*37)%W+20,y);ctx.stroke();}ctx.globalAlpha=1;
}
function drawBeam(){if(drive<=0)return;const a=4.5-drive,ww=54+Math.sin(a*.7)*35;ctx.save();ctx.globalAlpha=saved.reduced?.65:.88;const g=ctx.createLinearGradient(player.x-ww,0,player.x+ww,0);g.addColorStop(0,'#21ff9b00');g.addColorStop(.18,'#10e7a0');g.addColorStop(.38,'#e9ff35');g.addColorStop(.5,'#fffbc6');g.addColorStop(.62,'#e9ff35');g.addColorStop(.82,'#10e7a0');g.addColorStop(1,'#21ff9b00');ctx.fillStyle=g;ctx.beginPath();for(let side=-1;side<=1;side+=2){for(let j=0;j<=48;j++){const y=side===-1?player.y-j*(player.y+20)/48:-20+j*(player.y+20)/48;const neck=clamp((y-70)/90,0,1),width=ww*(.23+.77*neck);const x=player.x+side*(width+Math.sin(y*.047+t*9)*4);if(side===-1&&j===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}}ctx.closePath();ctx.fill();ctx.strokeStyle='#caff8a';ctx.lineWidth=2;ctx.globalAlpha=.45;ctx.stroke();ctx.restore();}
function draw(){ctx.save();if(shake&&!saved.reduced)ctx.translate(Math.sin(t*93)*shake,Math.cos(t*79)*shake);background();if(state==='title'){ctx.save();ctx.globalAlpha=.16;ctx.fillStyle='#ff553d';ctx.font='bold 120px monospace';ctx.translate(240,390);ctx.rotate(-.16);ctx.fillText('61/3',-165,0);ctx.restore();sprite('soju',W*.71,H*.58,133,174,-.27,1);sprite('soju',80,H*.57,56,80,.2,.75);sprite('vinyl',W*.85,130,67,72,t*.12,.7);}else{
 drawBeam();for(const d of drops){ctx.save();ctx.translate(d.x,d.y);ctx.fillStyle=d.type==='record'?'#302436':'#142827';ctx.strokeStyle=d.type==='power'?'#dfff55':d.type==='health'?'#66e4ff':'#ffcd62';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,12+Math.sin(d.age*5),0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.font='bold 12px monospace';ctx.textAlign='center';ctx.fillText(d.type==='power'?'P':d.type==='health'?'+':'●',0,4);ctx.restore();}
 for(const e of enemies){sprite(e.kind,e.x,e.y,e.w,e.h,e.kind==='vinyl'?e.age*.7:(e.kind==='soju'?Math.PI:0)+Math.sin(e.age*2)*.08);if(e.hit>0){ctx.globalAlpha=.5;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(e.x,e.y,12,0,TAU);ctx.fill();ctx.globalAlpha=1;}}
 if(boss){const name=stage===1?'vinyl':'boss';sprite(name,boss.x,boss.y,boss.w,boss.h,Math.sin(boss.age)*.035);if(boss.hit>0){ctx.strokeStyle='#fff5d0';ctx.lineWidth=2;ctx.beginPath();ctx.arc(boss.x,boss.y,60,0,TAU);ctx.stroke();}}
 ctx.lineCap='round';for(const s of shots){ctx.strokeStyle='#e4ffff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x-s.vx*.025,s.y+16);ctx.stroke();ctx.strokeStyle='#48d5ed';ctx.lineWidth=6;ctx.globalAlpha=.3;ctx.stroke();ctx.globalAlpha=1;}
 for(const b of bullets){ctx.fillStyle='#1c1434';ctx.strokeStyle=b.color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(b.x,b.y,b.r+1,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#fff6cf';ctx.beginPath();ctx.arc(b.x,b.y,1.7,0,TAU);ctx.fill();}
 for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.r*2,p.r);}ctx.globalAlpha=1;
 for(const r of rings){ctx.globalAlpha=r.life/.55;ctx.strokeStyle=r.color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,TAU);ctx.stroke();}ctx.globalAlpha=1;
 if(player.hp>0){const grow=drive>0?1+Math.sin(Math.min(1,(4.5-drive)*2)*Math.PI/2)*.85:1;ctx.fillStyle=drive>0?'#ff9b47':'#52eaff';ctx.globalAlpha=.7;ctx.beginPath();ctx.moveTo(player.x-6*grow,player.y+25*grow);ctx.lineTo(player.x,player.y+(40+Math.sin(t*40)*5)*grow);ctx.lineTo(player.x+6*grow,player.y+25*grow);ctx.fill();ctx.globalAlpha=1;sprite('soju',player.x,player.y,48*grow,65*grow,0,player.inv>0?.72:1);if(player.inv>0||drive>0){ctx.strokeStyle=drive>0?'#ffff85':'#66e7ff';ctx.globalAlpha=.5;ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(player.x,player.y,25*grow,0,TAU);ctx.stroke();ctx.globalAlpha=1;}ctx.fillStyle='#091b2c';ctx.beginPath();ctx.arc(player.x,player.y,5,0,TAU);ctx.fill();ctx.fillStyle='#6df9ff';ctx.beginPath();ctx.arc(player.x,player.y,2.5,0,TAU);ctx.fill();}
 if(transition>0){const tx=clamp((3.8-transition)*2,0,1);ctx.save();ctx.translate((1-tx)*W,0);for(let i=0;i<3;i++){ctx.fillStyle='#1e132cdd';ctx.strokeStyle=['#dfff42','#ff6d62','#cf8eff'][i];ctx.lineWidth=2;ctx.fillRect(50,275+i*53,380,43);ctx.strokeRect(50,275+i*53,380,43);ctx.fillStyle=ctx.strokeStyle;ctx.font='bold 14px monospace';ctx.fillText(i===0?'TRANSMISSION CLEARED':i===1?`NRK  /  ${String(score).padStart(6,'0')}`:'NEXT FREQUENCY →',67,302+i*53);}ctx.restore();}
 }ctx.fillStyle='#000';ctx.globalAlpha=saved.reduced?0:.06;for(let y=0;y<H;y+=4)ctx.fillRect(0,y,W,1);ctx.globalAlpha=1;ctx.restore();}
function hud(){$('score').textContent=String(score).padStart(6,'0');$('mult').textContent=1+Math.min(3,Math.floor(combo/12));$('lives').textContent=Array.from({length:3},(_,i)=>i<player.hp?'●':'○').join(' ');$('lives').setAttribute('aria-label',`${player.hp} shields remaining`);$('stage-name').textContent=`0${stage+1} / ${stages[stage].name}`;$('boss-hud').hidden=!boss;if(boss){$('boss-name').textContent=stages[stage].boss;$('boss-health').value=boss.hp/boss.max;}$('flight-status').textContent=drive>0?'OVERDRIVE ACTIVE':`TRANSMISSION 0${stage+1} / LIVE`;$('weapon-label').textContent=`FIREPOWER ${player.power}/3 · AUTO FIRE`;$('charge-fill').style.width=`${drive>0?drive/4.5*100:charge}%`;const can=charge>=100&&drive<=0&&state==='playing'&&transition<=0;$('overdrive-btn').disabled=!can;$('overdrive-btn').classList.toggle('ready',can);$('charge-label').textContent=drive>0?'SKY AT FULL VOLUME':can?'READY — PRESS X / TAP':`${Math.floor(charge)}% / CHARGING`;}
function frame(now){const elapsed=Math.min(.1,(now-last)/1000||0);last=now;if(!qaManual){if(state==='playing'||state==='title'){acc+=elapsed;let n=0;while(acc>=1/60&&n++<6){step(1/60);acc-=1/60;}}draw();}requestAnimationFrame(frame);}
function key(e,down){if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||$('settings').open||$('help').open)return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','a','s','d','Shift','x','p','Escape'].includes(k))e.preventDefault();if(down){if(!e.repeat){if(k==='p'||k==='Escape'){state==='playing'?pause():state==='paused'?resume():null;return;}if(k==='x')activateDrive();if((k==='Enter'||k===' ')&&state==='title'&&e.target===cv)start();}if(state==='playing')keys.add(k);}else keys.delete(k);}
addEventListener('keydown',e=>key(e,true));addEventListener('keyup',e=>key(e,false));
function point(e){const r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H};}
cv.addEventListener('pointerdown',e=>{if(state!=='playing'||pointer)return;e.preventDefault();unlockAudio();cv.focus({preventScroll:true});const p=point(e);pointer={id:e.pointerId,...p};try{cv.setPointerCapture(e.pointerId);}catch{pointer=null;}});
cv.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id||state!=='playing')return;const p=point(e);player.x=clamp(player.x+(p.x-pointer.x)*1.1,25,W-25);player.y=clamp(player.y+(p.y-pointer.y)*1.1,85,H-38);pointer={id:e.pointerId,...p};});
for(const ev of ['pointerup','pointercancel','lostpointercapture'])cv.addEventListener(ev,e=>{if(pointer?.id===e.pointerId)pointer=null;});
addEventListener('blur',()=>pause());document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
$('start-btn').onclick=start;$('retry-btn').onclick=start;$('resume-btn').onclick=resume;$('pause-btn').onclick=pause;$('overdrive-btn').onclick=activateDrive;$('quit-btn').onclick=()=>finish(false);$('menu-btn').onclick=title;$('save-btn').onclick=saveScore;
$('home-link').onclick=e=>{e.preventDefault();if(state==='playing')pause();else if(state!=='paused')title();};
function openDialog(id){pause();keys.clear();pointer=null;$(id).showModal();}
$('settings-btn').onclick=()=>openDialog('settings');$('how-btn').onclick=()=>openDialog('help');
for(const id of ['settings','help'])$(id).addEventListener('close',()=>{if(state==='paused')$('resume-btn').focus({preventScroll:true});else if(state==='title')$('start-btn').focus({preventScroll:true});});
$('sound').checked=!!saved.sound;$('reduced').checked=!!saved.reduced;$('difficulty').value=saved.difficulty;
$('sound').onchange=e=>{saved.sound=e.target.checked;persist();unlockAudio();};$('reduced').onchange=e=>{saved.reduced=e.target.checked;persist();};$('difficulty').onchange=e=>{saved.difficulty=e.target.value;persist();};
updateScores();requestAnimationFrame(frame);
// Opt-in local QA controls are absent from ordinary game sessions.
if(QA)window.__qa={start, pause,resume,activateDrive,hit:()=>{player.inv=0;takeHit();},state:()=>({state,stage,stageTime,score,kills,charge,drive,transition,player:{...player},boss:boss?{...boss}:null,enemies:enemies.length,bullets:bullets.length,particles:particles.length,shots:shots.length,totalSpawned,escaped,ready,storageOK}),advance(seconds){qaManual=true;for(let i=0;i<Math.round(seconds*60);i++)step(1/60);hud();draw();},manual(v){qaManual=v;last=performance.now();acc=0;},god(v){qaGod=v;},setPlayer(v){Object.assign(player,v);},charge(v){charge=v;hud();},setBossHP(v){if(boss)boss.hp=v;},clearEnemies(){for(const e of enemies)if(e.hp>0)destroyEnemy(e);},addDrop(type){drops.push({x:player.x,y:player.y,type,age:0});},bullet(){bullets.push({x:player.x,y:player.y,r:5,vx:0,vy:0,color:'#fff'});},draw,finish,stats:()=>({sprites:Object.keys(sprites),scores:saved.scores,settings:saved})};
})();
