'use strict';
(() => {
const $=id=>document.getElementById(id), cv=$('game'), ctx=cv.getContext('2d',{alpha:false});
const W=480,H=720,TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const STORE='nonrocker-overdrive-v1', QA=new URLSearchParams(location.search).has('qa');
const stages=[
 {name:'ACID COAST',boss:'THE BOTTLE SERVICE',base:'#130e29',hot:'#e94328',cool:'#18378c',duration:52,hp:900},
 {name:'COBALT RIOT',boss:'FEEDBACK MACHINE',base:'#0b152b',hot:'#1533cb',cool:'#953f9e',duration:58,hp:1250},
 {name:'MOLTEN FREQUENCY',boss:'LAST CALL / NRK–666',base:'#211020',hot:'#ff6f12',cool:'#ad224a',duration:64,hp:1700}
];
let saved={scores:[],sound:false,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,difficulty:'normal'};
try { const raw=JSON.parse(localStorage.getItem(STORE)||'null');if(raw&&typeof raw==='object')saved={...saved,...raw}; }catch{}
saved.scores=Array.isArray(saved.scores)?saved.scores.filter(s=>s&&Number.isFinite(s.score)&&typeof s.name==='string').slice(0,8):[];
saved.difficulty=saved.difficulty==='chill'?'chill':'normal';
let storageOK=true;
function persist(){try{localStorage.setItem(STORE,JSON.stringify(saved));}catch{storageOK=false;}}
let seed=613;function rnd(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}const rand=(a,b)=>a+rnd()*(b-a);
let state='title',t=0,runTime=0,stage=0,stageTime=0,nextWave=1,wave=0,score=0,kills=0,combo=0,comboTimer=0,charge=0,drive=0,driveHit=0;
let enemies=[],shots=[],bullets=[],particles=[],drops=[],rings=[],boss=null,transition=0,noticeTimer=0,shake=0,savedRun=false,difficulty='normal',endingWin=false;
let player={x:240,y:614,hp:3,power:1,inv:0,fire:0}, keys=new Set(),pointer=null,ready=false,last=0,acc=0,hudClock=0;
let totalSpawned=0,escaped=0,qaGod=false,qaManual=false,travel=0,damageFlash=0;
let bombs=2,rank=0,freeze=0,flash=0,boom=null;
const SPREADS=[[0],[-.06,.06],[-.12,0,.12],[-.17,-.06,.06,.17],[-.24,-.12,0,.12,.24]];
const pickupStyle={record:{color:'#ffd56a',symbol:'$',label:'CHARGE'},power:{color:'#dcff42',symbol:'P',label:'POWER'},health:{color:'#69edff',symbol:'+',label:'SHIELD'},bomb:{color:'#ff8dff',symbol:'B',label:'BOMB'}};
let callouts=[];
function feedback(x,y,text,color){callouts.push({x,y,text,color,life:1.1});callouts=callouts.slice(-8);}
// Preserve logical collision coordinates while rendering sharply on larger displays.
function resizeCanvas(){const size=cv.getBoundingClientRect(),scale=Math.min(3,Math.max(1,size.width/W*(devicePixelRatio||1)));cv.width=Math.round(W*scale);cv.height=Math.round(H*scale);ctx.setTransform(cv.width/W,0,0,cv.height/H,0,0);}
new ResizeObserver(resizeCanvas).observe(cv);
// Custom atlas bounds accommodate the generated sprites' different silhouettes.
const atlas=new Image(),terrain=new Image();let atlasReady=false,terrainReady=false;
function assetsReady(){ready=atlasReady&&terrainReady;if(ready){$('start-btn').disabled=false;$('start-btn').textContent='START FLIGHT →';}}
const rects={jet:[8,32,396,510],soju:[447,34,369,507],vinyl:[850,61,395,482],kazoo:[4,575,324,648],boss:[335,565,563,654],moth:[897,620,350,568]};
const sprites={};
atlas.onload=()=>{for(const [name,r]of Object.entries(rects)){const c=document.createElement('canvas');c.width=r[2];c.height=r[3];c.getContext('2d').drawImage(atlas,...r,0,0,r[2],r[3]);sprites[name]=c;}atlasReady=true;assetsReady();};
atlas.onerror=()=>{$('start-btn').textContent='ART FAILED TO LOAD — RELOAD';$('flight-status').textContent='CHECK LOCAL ASSET FILE';};
terrain.onload=()=>{terrainReady=true;assetsReady();};terrain.onerror=atlas.onerror;
atlas.src='assets/nonrocker-atlas.png';terrain.src='assets/signal-terrain.png';
const extra={},stageTerrain=[];
for(const n of['popup','amp','cassette','spikemine','odm','boss1','boss2','fx0','fx1','fx2','fx3','fx4','fx5']){const im=new Image();im.onload=()=>{extra[n]=im;};im.src=`assets/${n}.png?v=4`;}
for(let i=0;i<3;i++){const im=new Image();im.onload=()=>{stageTerrain[i]=im;};im.src=`assets/terrain${i}.jpg?v=4`;}
const SKIN={soju:['popup'],moth:['cassette'],vinyl:['spikemine'],kazoo:['amp']};
const fxBursts=[];
function fxBurst(x,y,idx,size){if(!extra['fx'+idx]||fxBursts.length>28)return;fxBursts.push({x,y,idx,size,t:0,dur:.38+size*.05,rot:rand(-.4,.4)});}

// All audio is synthesized locally after a user gesture.
let audio=null,musicStep=0,musicTimer=0;
function unlockAudio(){if(!saved.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{saved.sound=false;$('sound').checked=false;}}
function tone(freq,duration=.08,type='sine',volume=.03,end=freq){if(!saved.sound||!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain(),n=audio.currentTime;o.type=type;o.frequency.setValueAtTime(freq,n);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),n+duration);g.gain.setValueAtTime(volume,n);g.gain.exponentialRampToValueAtTime(.0001,n+duration);o.connect(g);g.connect(audio.destination);o.start(n);o.stop(n+duration+.01);}
function music(dt){if(!saved.sound)return;musicTimer-=dt;if(musicTimer>0)return;musicTimer=.19;const notes=[55,55,82.41,55,65.41,55,98,73.42];tone(notes[musicStep%8]*(stage===1?1.122:1),.16,'triangle',.045);if(musicStep%4===0)tone(140,.12,'sine',.08,35);if(musicStep%2===1)tone(2600,.035,'square',.006,1300);if(musicStep%8===6)tone(330,.12,'sine',.02,660);musicStep++;}
const bulletCache={};
function bulletImg(r){if(bulletCache[r])return bulletCache[r];const half=r+6,c=document.createElement('canvas'),g2=(c.width=c.height=half*6,c.getContext('2d')),q=r+3;c.half=half;g2.translate(half*3,half*3);g2.scale(3,3);g2.strokeStyle='#050510';g2.lineWidth=4;g2.fillStyle='#ff365b';g2.beginPath();g2.moveTo(0,-q);g2.lineTo(q,0);g2.lineTo(0,q);g2.lineTo(-q,0);g2.closePath();g2.stroke();g2.fill();g2.strokeStyle='#ffccd2';g2.lineWidth=1;g2.stroke();g2.fillStyle='#fff';g2.fillRect(-1.5,-1.5,3,3);return bulletCache[r]=c;}
function sprite(name,x,y,w,h,angle=0,alpha=1){if(!sprites[name])return;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.globalAlpha=alpha;ctx.drawImage(sprites[name],-w/2,-h/2,w,h);ctx.restore();}
function puff(x,y,color,count=12,speed=110){for(let i=0;i<count&&particles.length<520;i++){const a=rand(0,TAU),v=rand(speed*.2,speed);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rand(.2,.65),max:.65,r:rand(1,4),color});}}
function blast(x,y,color,size=1){fxBurst(x,y,size>2.5?5:size>1.5?1:color==='#b6ff65'?4:color==='#ff8dff'?3:rnd()<.3?2:0,size);puff(x,y,color,Math.round(14*size),160*size);puff(x,y,'#fff6c8',Math.round(6*size),90*size);ring(x,y,color,6*size);if(size>1.5){ring(x,y,'#fff',14);if(!saved.reduced)shake=Math.max(shake,5*size);}}
function ring(x,y,color,r=8){if(rings.length<24)rings.push({x,y,r,life:.55,color});}
function notify(s,duration=2.1){$('notice').textContent=s;$('notice').classList.add('show');noticeTimer=duration;}
function screen(id){for(const s of ['title-screen','pause-screen','result-screen'])$(s).hidden=s!==id;}
function updateScores(){const best=Math.max(0,...saved.scores.map(s=>s.score));$('best-score').textContent=String(best).padStart(6,'0');$('score-list').replaceChildren();saved.scores.slice(0,5).forEach((s,i)=>{const li=document.createElement('li');li.append(`${String(s.name).slice(0,3)} / ${s.mode==='chill'?'CHILL':'ARCADE'}`);const n=document.createElement('span');n.textContent=String(s.score).padStart(6,'0');li.append(n);$('score-list').append(li);});}
function resetStage(){stageTime=0;nextWave=1;wave=0;enemies=[];shots=[];bullets=[];drops=[];boss=null;transition=0;player.x=W/2;player.y=610;player.inv=2;notify(`TRANSMISSION 0${stage+1}\n${stages[stage].name}`,2.7);}
function start(){if(!ready)return;seed=613;state='playing';runTime=0;stage=0;score=0;kills=0;combo=0;charge=30;drive=0;comboTimer=0;totalSpawned=0;escaped=0;particles=[];rings=[];fxBursts.length=0;callouts=[];damageFlash=0;bombs=2;rank=0;freeze=0;flash=0;boom=null;savedRun=false;endingWin=false;difficulty=saved.difficulty;player={x:240,y:614,hp:3,power:1,inv:2,fire:0};keys.clear();pointer=null;resetStage();screen(null);$('hud').hidden=false;$('pause-btn').disabled=false;$('save-btn').disabled=false;$('save-btn').textContent='SAVE LOCAL SCORE';unlockAudio();cv.focus({preventScroll:true});hud();}
function title(){state='title';keys.clear();pointer=null;screen('title-screen');$('hud').hidden=true;$('pause-btn').disabled=true;$('overdrive-btn').disabled=true;$('bomb-btn').disabled=true;$('notice').classList.remove('show');$('flight-status').textContent='READY TO TRANSMIT';$('weapon-label').textContent='AUTO FIRE / DRAG TO STEER';$('charge-fill').style.width='0%';$('charge-label').textContent='BUILD YOUR CHARGE';$('overdrive-btn').classList.remove('ready');updateScores();}
function pause(){if(state!=='playing')return;state='paused';keys.clear();pointer=null;screen('pause-screen');$('pause-btn').disabled=true;$('overdrive-btn').disabled=true;$('bomb-btn').disabled=true;$('flight-status').textContent='TRANSMISSION PAUSED';$('resume-btn').focus({preventScroll:true});}
function resume(){if(state!=='paused')return;state='playing';screen(null);$('pause-btn').disabled=false;last=performance.now();acc=0;unlockAudio();cv.focus({preventScroll:true});hud();}
function finish(win){state='result';endingWin=win;drive=0;pointer=null;keys.clear();screen('result-screen');$('hud').hidden=true;$('notice').classList.remove('show');$('pause-btn').disabled=true;$('overdrive-btn').disabled=true;$('bomb-btn').disabled=true;$('result-kicker').textContent=win?'ALL TRANSMISSIONS CLEARED':'END OF TRANSMISSION';$('result-title').innerHTML=win?'NOISE<br>FOREVER.':'SIGNAL<br>LOST.';$('final-score').textContent=String(score).padStart(6,'0');$('result-detail').textContent=`${kills} TAKEDOWNS / STAGE ${stage+1} / ${difficulty.toUpperCase()}`;$('flight-status').textContent=win?'ALL STAGES CLEARED':'FLIGHT COMPLETE';updateScores();$('retry-btn').focus({preventScroll:true});tone(win?523:110,.5,'triangle',.08,win?1046:45);}
function saveScore(){if(state!=='result'||savedRun)return;const name=$('initials').value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,3)||'NRK';saved.scores.push({name,score,mode:difficulty,clear:endingWin,date:new Date().toISOString().slice(0,10)});saved.scores.sort((a,b)=>b.score-a.score);saved.scores=saved.scores.slice(0,8);persist();savedRun=true;$('save-btn').disabled=true;$('save-btn').textContent=storageOK?'SCORE SAVED ON THIS DEVICE':'SAVED FOR THIS SESSION ONLY';updateScores();}
function addScore(n){score+=Math.round(n*(1+Math.min(3,Math.floor(combo/12))));}
function takeHit(){if(player.inv>0||drive>0||qaGod)return;player.hp--;player.power=Math.max(1,player.power-1);player.inv=2.2;combo=0;damageFlash=.35;rank=Math.max(0,rank-.25);freeze=Math.max(freeze,.09);bullets=bullets.filter(b=>Math.hypot(b.x-player.x,b.y-player.y)>130);feedback(player.x,player.y-42,'SHIELD LOST','#ff7585');shake=saved.reduced?0:9;puff(player.x,player.y,'#ff6847',20,180);ring(player.x,player.y,'#ff536b',15);tone(100,.25,'sawtooth',.055,30);if(player.hp<=0)finish(false);}
function activateDrive(){if(state!=='playing'||charge<100||drive>0||transition>0)return;charge=0;drive=4.5;driveHit=0;bullets=[];flash=saved.reduced?.2:.7;ring(player.x,player.y,'#edff7a',50);tone(90,.7,'sawtooth',.045,600);notify('OVERDRIVE\nMAKE THE SKY LOUD',1.4);hud();}
function bombNow(){if(state!=='playing'||bombs<1||transition>0)return;bombs--;player.inv=Math.max(player.inv,1.8);bullets=[];for(const e of enemies)if(e.hp>0&&e.y>-30){e.hp-=25;e.hit=.1;if(e.hp<=0)destroyEnemy(e);}if(boss&&boss.y>-20){boss.hp-=70;boss.hit=.1;}flash=saved.reduced?.3:1;freeze=.1;if(!saved.reduced)shake=Math.max(shake,14);ring(player.x,player.y,'#ff8dff',20);ring(player.x,player.y,'#fff',60);blast(player.x,player.y,'#ff8dff',3);notify('FORM / BOMB\nSCREEN ERASED',1.1);tone(70,.6,'sawtooth',.06,700);hud();}
function spawnEnemy(kind,x,y,pattern='sway',o={}){const specs={soju:[4,44,65,24,180],vinyl:[9,58,61,26,260],kazoo:[13,45,86,27,350],moth:[4,50,65,24,220],odm:[70,100,132,46,1500]},s=specs[kind];enemies.push({kind,x,y,baseX:x,age:0,hp:s[0]+stage*3,w:s[1],h:s[2],r:s[3],points:s[4],vy:(o.vy??rand(105,145))+stage*14,vx:o.vx||0,amp:o.amp??28,phase:o.phase??rand(0,TAU),fire:rand(.7,1.9),pattern,hit:0,skin:kind==='odm'?'odm':(SKIN[kind]&&extra[SKIN[kind][0]]&&rnd()<.5)?SKIN[kind][0]:null});totalSpawned++;}
function spawnWave(){const w=wave++,k=[['soju','moth'],['soju','moth','vinyl'],['soju','moth','vinyl','kazoo']][stage],a=k[w%k.length],b=k[(w+1)%k.length],heavy=b==='soju'?'vinyl':b,f=w%6;if(extra.odm&&w%8===7)spawnEnemy('odm',W/2,-80,'sway',{amp:80,vy:52});
 if(f===0){for(let i=0;i<7;i++)spawnEnemy(a,W/2+(i-3)*50,-40-Math.abs(i-3)*38,'sway',{amp:10});}
 else if(f===1){for(let i=0;i<8;i++)spawnEnemy(a,45+i*(W-90)/7,-40-(i%2)*34,'sway',{amp:14});}
 else if(f===2){for(let i=0;i<5;i++){spawnEnemy(b,-10,-40-i*44,'sway',{vx:82,amp:8});spawnEnemy(b,W+10,-40-i*44,'sway',{vx:-82,amp:8});}}
 else if(f===3){for(let i=0;i<10;i++)spawnEnemy('moth',rand(40,W-40),-40-i*30,'swoop',{amp:70,vy:rand(150,190)});}
 else if(f===4){for(let i=0;i<4;i++){spawnEnemy(heavy,110,-40-i*70,'sway',{amp:6,vy:95});spawnEnemy(heavy,W-110,-40-i*70,'sway',{amp:6,vy:95});}}
 else{const c=stage>0?'kazoo':'vinyl';spawnEnemy(c,W/2,-60,'sway',{amp:90,vy:85});for(let i=0;i<6;i++)spawnEnemy(a,60+i*72,-30-((i+1)%2)*40,'sway',{amp:12});}}
const fireGap={soju:2.9,moth:2.3,vinyl:3.2,kazoo:2.6,odm:1.7};
function enemyFire(e){e.fire=fireGap[e.kind]*(1.15-stage*.1)*(1-rank*.35)*rand(.85,1.15);const a=aim(e.x,e.y),sp=125+stage*18+rank*30;
 if(e.kind==='odm'){for(let i=-3;i<=3;i++)enemyShot(e.x,e.y+30,a+i*.17,sp*.85,5,'#ffb800');if(rnd()<.5){const n=10,o=rnd()*TAU;for(let i=0;i<n;i++)enemyShot(e.x,e.y,o+i*TAU/n,sp*.6,5,'#ff7ad9');}}
 else if(e.kind==='soju')enemyShot(e.x,e.y,a,sp);
 else if(e.kind==='moth'){enemyShot(e.x,e.y,a-.1,sp+10);enemyShot(e.x,e.y,a+.1,sp+10);}
 else if(e.kind==='vinyl'){const n=8+stage*2+Math.round(rank*4),o=rnd()*TAU;for(let i=0;i<n;i++)enemyShot(e.x,e.y,o+i*TAU/n,sp*.7,5,'#ff7ad9');}
 else{const n=3+stage+Math.round(rank*2);for(let i=-n;i<=n;i++)enemyShot(e.x,e.y,a+i*.16,sp*.9);}}
function enemyShot(x,y,angle,speed=110,r=5,color='#ffbf57'){if(bullets.length>=300)return;const mul=difficulty==='chill'?.67:1;bullets.push({x,y,vx:Math.cos(angle)*speed*mul,vy:Math.sin(angle)*speed*mul,r,color});}
function aim(x,y,spread=0){return Math.atan2(player.y-y,player.x-x)+spread;}
function destroyEnemy(e){e.hp=0;combo++;comboTimer=3.5;kills++;charge=clamp(charge+4,0,100);addScore(e.points);rank=Math.min(1,rank+.006);const big=e.kind==='kazoo'||e.kind==='vinyl'||e.kind==='odm';blast(e.x,e.y,e.kind==='soju'?'#b6ff65':'#ff8962',big?1.6:.8);if(big)freeze=Math.max(freeze,.05);ring(e.x,e.y,'#f5efb2');tone(100+Math.min(combo,20)*12,.07,'triangle',.023,50);const type=kills%9===0?'power':kills%23===0?'health':kills%17===0?'bomb':'record';if(type!=='record'||kills%3===0)drops.push({x:e.x,y:e.y,type,age:0});}
function spawnBoss(){boss={x:W/2,y:-100,hp:stages[stage].hp,max:stages[stage].hp,age:0,fire:1.7,ring:2.4,hit:0,w:extra['boss'+stage]?200*extra['boss'+stage].width/extra['boss'+stage].height:(stage===1?150:180),h:extra['boss'+stage]?200:175};enemies=[];bullets=[];notify(`WARNING / HEAVY SIGNAL\n${stages[stage].boss}`,2.6);tone(220,.4,'triangle',.04,110);}
function beatBoss(){if(!boss)return;addScore(5000*(stage+1));kills++;blast(boss.x,boss.y,'#fcff70',3);ring(boss.x,boss.y,'#64eaff',60);boom={x:boss.x,y:boss.y,t:1.8,n:0};flash=.9;freeze=.12;bombs=Math.min(5,bombs+1);boss=null;bullets=[];enemies=[];drops=[];shots=[];drive=0;transition=3.8;player.hp=Math.min(3,player.hp+1);player.power=Math.min(5,player.power+1);player.inv=5;charge=clamp(charge+30,0,100);notify(`TRANSMISSION 0${stage+1} COMPLETE\n+ SHIELD / + FIREPOWER / + BOMB`,3.6);tone(440,.3,'triangle',.05,880);}
function step(dt){t+=dt;travel+=dt*(saved.reduced?30:state==='title'?70:drive>0?520:290+stage*40);damageFlash=Math.max(0,damageFlash-dt);flash=Math.max(0,flash-dt*2.2);for(const c of callouts){c.y-=dt*24;c.life-=dt;}callouts=callouts.filter(c=>c.life>0);if(state!=='playing')return;if(freeze>0){freeze-=dt;return;}runTime+=dt;stageTime+=dt;music(dt);noticeTimer-=dt;if(noticeTimer<=0)$('notice').classList.remove('show');shake=Math.max(0,shake-dt*28);player.inv=Math.max(0,player.inv-dt);comboTimer-=dt;if(comboTimer<=0)combo=0;charge=clamp(charge+dt*1.7,0,100);drive=Math.max(0,drive-dt);
 let mx=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0),my=(keys.has('ArrowDown')||keys.has('s')?1:0)-(keys.has('ArrowUp')||keys.has('w')?1:0);const norm=Math.hypot(mx,my)||1,speed=keys.has('Shift')?140:340;player.x=clamp(player.x+mx/norm*speed*dt,25,W-25);player.y=clamp(player.y+my/norm*speed*dt,85,H-38);
 if(transition>0){transition-=dt;if(transition<=0){if(stage===2){finish(true);return;}stage++;resetStage();}}else{
 if(!boss&&stageTime<stages[stage].duration&&stageTime>=nextWave){spawnWave();nextWave+=Math.max(.9,1.55-stage*.15-rank*.2);}
 if(!boss&&stageTime>=stages[stage].duration)spawnBoss();
 player.fire-=dt;if(player.fire<=0){player.fire=drive>0?.06:.085;for(const a of SPREADS[player.power-1])shots.push({x:player.x,y:player.y-25,vx:Math.sin(a)*780,vy:-Math.cos(a)*780,r:4});if(Math.floor(runTime*7)%3===0)tone(660,.035,'triangle',.008,380);}
 }
 for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;}
 for(const e of enemies){e.age+=dt;e.hit=Math.max(0,e.hit-dt);e.y+=e.vy*dt;e.baseX+=e.vx*dt;e.x=clamp(e.baseX+Math.sin(e.age*(e.pattern==='swoop'?1.8:1)+e.phase)*(e.pattern==='swoop'?Math.max(65,e.amp):e.amp),22,W-22);e.fire-=dt;if(e.fire<=0&&e.y>35&&e.y<player.y-30)enemyFire(e);
  if(Math.hypot(e.x-player.x,e.y-player.y)<e.r+6)takeHit();if(state!=='playing')return;
 }
 if(boss){boss.age+=dt;boss.y=Math.min(145,boss.y+55*dt);boss.x=240+Math.sin(boss.age*.85)*140;boss.hit=Math.max(0,boss.hit-dt);boss.fire-=dt;if(boss.y>60&&boss.fire<=0){boss.fire=(stage===2?.5:.7)*(1-rank*.25);const a=aim(boss.x,boss.y),count=stage+3;for(let i=-count;i<=count;i++)enemyShot(boss.x,boss.y+42,a+i*.15,130+stage*15,5,'#ffaf6d');}if(boss.y>60){boss.ring-=dt;if(boss.ring<=0){boss.ring=2.6-stage*.4;const n=16+stage*4;for(let i=0;i<n;i++)enemyShot(boss.x,boss.y,i*TAU/n+boss.age*.5,88,4,'#fca3fc');}}if(Math.hypot(boss.x-player.x,boss.y-player.y)<72)takeHit();if(state!=='playing')return;}
 for(const s of shots){if(s.dead)continue;for(const e of enemies){if(e.hp>0&&Math.hypot(s.x-e.x,s.y-e.y)<e.r+s.r){s.dead=true;e.hp--;e.hit=.07;if(e.hp<=0)destroyEnemy(e);break;}}if(!s.dead&&boss&&Math.abs(s.x-boss.x)<boss.w*.38&&Math.abs(s.y-boss.y)<boss.h*.39){s.dead=true;boss.hp--;boss.hit=.06;}}
 if(drive>0){driveHit-=dt;const beamW=55+Math.sin((4.5-drive)*.7)*30;bullets=bullets.filter(b=>Math.abs(b.x-player.x)>beamW||b.y>player.y);if(driveHit<=0){driveHit=.08;for(const e of enemies)if(e.hp>0&&e.y<player.y&&Math.abs(e.x-player.x)<beamW+e.r){e.hp-=4;e.hit=.06;if(e.hp<=0)destroyEnemy(e);}if(boss&&boss.y<player.y&&Math.abs(boss.x-player.x)<beamW+boss.w*.35){boss.hp-=5;boss.hit=.05;}}}
 if(boss&&boss.hp<=0)beatBoss();
 for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;if(Math.hypot(b.x-player.x,b.y-player.y)<b.r+5){b.dead=true;takeHit();if(state!=='playing')return;}}
 for(const d of drops){d.age+=dt;d.y+=90*dt;if(Math.hypot(d.x-player.x,d.y-player.y)<95){const a=aim(d.x,d.y);d.x+=Math.cos(a)*180*dt;d.y+=Math.sin(a)*180*dt;}if(Math.hypot(d.x-player.x,d.y-player.y)<24){d.dead=true;const ps=pickupStyle[d.type];ring(player.x,player.y,ps.color,10);if(d.type==='power'){const maxed=player.power>=5;player.power=Math.min(5,player.power+1);addScore(150);feedback(player.x,player.y-40,maxed?'MAX POWER / + SCORE':'POWER +1',ps.color);}else if(d.type==='bomb'){const full=bombs>=5;bombs=Math.min(5,bombs+1);if(full)addScore(200);feedback(player.x,player.y-40,full?'BOMBS FULL / + SCORE':'BOMB +1',ps.color);}else if(d.type==='health'){const full=player.hp>=3;player.hp=Math.min(3,player.hp+1);feedback(player.x,player.y-40,full?'SHIELDS FULL':'SHIELD +1',ps.color);}else{charge=clamp(charge+5,0,100);addScore(80);feedback(player.x,player.y-40,'+ SCORE / CHARGE',ps.color);}tone(880,.07,'sine',.022,1320);}}
 if(boom){boom.t-=dt;boom.n-=dt;if(boom.n<=0){boom.n=.09;blast(boom.x+rand(-75,75),boom.y+rand(-70,70),rnd()<.5?'#ffd25a':'#ff5a3a',1.4);tone(80+rand(0,120),.12,'sawtooth',.03,30);}if(boom.t<=0)boom=null;}
 for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;p.vx*=.98;p.vy*=.98;}for(const r of rings){r.r+=150*dt;r.life-=dt;}for(const f of fxBursts)f.t+=dt;while(fxBursts.length&&fxBursts[0].t>fxBursts[0].dur)fxBursts.shift();
 escaped+=enemies.filter(e=>e.hp>0&&e.y>H+100).length;enemies=enemies.filter(e=>e.hp>0&&e.y<H+100);shots=shots.filter(s=>!s.dead&&s.y>-30&&s.x>-10&&s.x<W+10).slice(-160);bullets=bullets.filter(b=>!b.dead&&b.y>-30&&b.y<H+30&&b.x>-30&&b.x<W+30);particles=particles.filter(p=>p.life>0);rings=rings.filter(r=>r.life>0);drops=drops.filter(d=>!d.dead&&d.y<H+25);hudClock-=dt;if(hudClock<=0){hudClock=.08;hud();}}

// Procedural scenery and typography animate independently from the vertical flight.
function background(){const st=stages[stage],clock=t,rate=saved.reduced?.22:1;ctx.fillStyle=st.base;ctx.fillRect(0,0,W,H);
 const layerT=clock*rate;
 const stx=stageTerrain[stage];if(stx){const th=740,offset=(travel*.7)%(th*2);ctx.globalAlpha=.85;for(let i=-2;i<2;i++){ctx.save();ctx.translate(-40+Math.sin(layerT*.12)*10,offset+i*th);if(Math.abs(i)%2){ctx.translate(0,th);ctx.scale(1,-1);}ctx.drawImage(stx,0,0,560,th);ctx.restore();}ctx.globalAlpha=1;}else if(terrainReady){const th=720,offset=(travel*.7)%(th*2);ctx.globalAlpha=.48;for(let i=-2;i<2;i++){ctx.save();ctx.translate(-70+Math.sin(layerT*.12)*20,offset+i*th);if(Math.abs(i)%2){ctx.translate(0,th);ctx.scale(1,-1);}ctx.drawImage(terrain,0,0,620,th);ctx.restore();}ctx.globalAlpha=1;}
 for(let layer=0;layer<3;layer++){ctx.globalAlpha=layer===0?.15:.08;ctx.fillStyle=layer===0?st.cool:layer===1?st.hot:'#effb51';ctx.beginPath();ctx.moveTo(0,H);for(let x=0;x<=W+12;x+=12){const yy=390+Math.sin(x*.013+layerT*.22+layer*2)*170+Math.sin(x*.033-layerT*.18+layer)*70;ctx.lineTo(x,yy);}ctx.lineTo(W,H);ctx.closePath();ctx.fill();}
 // Distorted ribbons travel from left to right, exposing the dark flight lane.
 for(let i=0;i<9;i++){const x=((i*93+layerT*(18+i%3*9))%(W+220))-110;ctx.globalAlpha=saved.reduced?.035:.075;ctx.fillStyle=i%3===0?'#d6fb39':i%3===1?st.hot:st.cool;ctx.beginPath();for(let y=-20;y<H+30;y+=16){const dx=Math.sin(y*.021+layerT*.6+i)*18+Math.sin(y*.047+i)*7;const px=x+dx;if(y===-20)ctx.moveTo(px,y);else ctx.lineTo(px,y);}for(let y=H+30;y>=-20;y-=16)ctx.lineTo(x+18+Math.sin(y*.021+layerT*.6+i)*18,y);ctx.closePath();ctx.fill();}
 ctx.globalAlpha=saved.reduced?.04:.11;ctx.fillStyle='#22f0bc';ctx.font='bold 136px monospace';const nums=['61','3','99','NRK'];for(let i=0;i<3;i++)ctx.fillText(nums[(Math.floor(layerT/5)+i)%4],W-165,((layerT*24+i*270)%1000)-90);
 const dark=ctx.createLinearGradient(0,0,W,0);dark.addColorStop(0,'#08091a33');dark.addColorStop(.3,'#08091a99');dark.addColorStop(.7,'#08091a99');dark.addColorStop(1,'#08091a33');ctx.globalAlpha=1;ctx.fillStyle=dark;ctx.fillRect(0,0,W,H);
 // Long edge streaks and slower distant dust make forward speed legible.
 ctx.save();ctx.lineCap='round';for(let i=0;i<44;i++){const depth=1+(i%3)*.65,x=(i*137.53)%W,y=(i*83.71+travel*depth)%(H+100)-50,edge=x<100||x>W-100;ctx.globalAlpha=saved.reduced?.07:edge?.26:.1;ctx.strokeStyle=i%3===0?'#73bfdd':'#b3b9de';ctx.lineWidth=edge?1.4:.8;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y+(edge?22:5)*depth*(drive>0?1.7:1));ctx.stroke();}ctx.restore();
 for(let side=0;side<2;side++){ctx.strokeStyle=st.hot;ctx.lineWidth=2;ctx.globalAlpha=.28;for(let i=0;i<7;i++){const y=(i*135+travel*1.5)%945-100,x=side?W-18:18;ctx.beginPath();ctx.moveTo(x-7,y);ctx.lineTo(x,y+10);ctx.lineTo(x+7,y);ctx.stroke();}}ctx.globalAlpha=1;
 ctx.font='12px monospace';ctx.fillStyle='#ff342e';ctx.globalAlpha=saved.reduced?.08:.32;const offset=(layerT*30)%21;for(let i=-1;i<36;i++){const num=((i+40)*7349+Math.floor(layerT/3)*61)%99999;ctx.fillText(`${['NRK','JDH','SOJ','61/','AWV'][((i+40)%5)]}-${String(num).padStart(5,'0')}`,8,i*21+offset);}
 ctx.font='7px monospace';ctx.fillStyle='#f54ed2';ctx.globalAlpha=saved.reduced?.07:.25;for(let i=-1;i<65;i++)ctx.fillText(['NONROCKER','RECOMBINE','FORM.BOMB','NOISE.613'][(i+65)%4],424,i*12-(layerT*18%12));ctx.globalAlpha=.24;ctx.font='9px monospace';ctx.fillStyle='#4868ff';for(let i=0;i<7;i++)ctx.fillText('FORM / BOMB',i*78-(layerT*8%78),75);
 ctx.globalAlpha=.1;ctx.strokeStyle='#bcc7f4';ctx.lineWidth=1;for(let i=0;i<15;i++){let y=(i*67+layerT*95)%H;ctx.beginPath();ctx.moveTo((i*37)%W,y);ctx.lineTo((i*37)%W+20,y);ctx.stroke();}ctx.globalAlpha=1;
}
function drawBeam(){if(drive<=0)return;const a=4.5-drive,ww=54+Math.sin(a*.7)*35;ctx.save();ctx.globalAlpha=saved.reduced?.65:.88;const g=ctx.createLinearGradient(player.x-ww,0,player.x+ww,0);g.addColorStop(0,'#21ff9b00');g.addColorStop(.18,'#10e7a0');g.addColorStop(.38,'#e9ff35');g.addColorStop(.5,'#fffbc6');g.addColorStop(.62,'#e9ff35');g.addColorStop(.82,'#10e7a0');g.addColorStop(1,'#21ff9b00');ctx.fillStyle=g;ctx.beginPath();for(let side=-1;side<=1;side+=2){for(let j=0;j<=48;j++){const y=side===-1?player.y-j*(player.y+20)/48:-20+j*(player.y+20)/48;const neck=clamp((y-70)/90,0,1),width=ww*(.23+.77*neck);const x=player.x+side*(width+Math.sin(y*.047+t*9)*4);if(side===-1&&j===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}}ctx.closePath();ctx.fill();ctx.strokeStyle='#caff8a';ctx.lineWidth=2;ctx.globalAlpha=.45;ctx.stroke();ctx.restore();}
function draw(){ctx.save();if(shake&&!saved.reduced)ctx.translate(Math.sin(t*93)*shake,Math.cos(t*79)*shake);background();if(state==='title'){ctx.save();ctx.globalAlpha=.16;ctx.fillStyle='#ff553d';ctx.font='bold 120px monospace';ctx.translate(240,390);ctx.rotate(-.16);ctx.fillText('61/3',-165,0);ctx.restore();sprite('soju',W*.71,H*.58,133,174,-.27,1);sprite('soju',80,H*.57,56,80,.2,.75);sprite('vinyl',W*.85,130,67,72,t*.12,.7);}else{
 drawBeam();for(const d of drops){const ps=pickupStyle[d.type];ctx.save();ctx.translate(d.x,d.y);ctx.shadowColor=ps.color;ctx.shadowBlur=saved.reduced?0:10;ctx.fillStyle='#081721';ctx.strokeStyle=ps.color;ctx.lineWidth=2.5;ctx.beginPath();ctx.roundRect(-15,-15,30,30,6);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=ps.color;ctx.font='bold 19px monospace';ctx.textAlign='center';ctx.fillText(ps.symbol,0,7);ctx.fillStyle='#070d17';ctx.fillRect(-24,19,48,13);ctx.fillStyle=ps.color;ctx.font='bold 8px monospace';ctx.fillText(ps.label,0,28);ctx.restore();}
 for(const e of enemies){if(e.skin){const im=extra[e.skin],k=Math.min(e.w*1.3/im.width,e.h*1.3/im.height);ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.skin==='spikemine'?e.age*.9:Math.sin(e.age*2)*.08);ctx.drawImage(im,-im.width*k/2,-im.height*k/2,im.width*k,im.height*k);ctx.restore();}else sprite(e.kind,e.x,e.y,e.w,e.h,e.kind==='vinyl'?e.age*.7:(e.kind==='soju'?Math.PI:0)+Math.sin(e.age*2)*.08);ctx.strokeStyle='#ff5975';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(e.x-8,e.y+e.h*.4);ctx.lineTo(e.x,e.y+e.h*.4+6);ctx.lineTo(e.x+8,e.y+e.h*.4);ctx.stroke();if(e.hit>0){ctx.globalAlpha=.5;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(e.x,e.y,12,0,TAU);ctx.fill();ctx.globalAlpha=1;}}
 if(boss){const bx=extra['boss'+stage];if(bx){ctx.save();ctx.translate(boss.x,boss.y);ctx.rotate(Math.sin(boss.age)*.03);ctx.drawImage(bx,-boss.w/2,-boss.h/2,boss.w,boss.h);ctx.restore();}else{const name=stage===1?'vinyl':'boss';sprite(name,boss.x,boss.y,boss.w,boss.h,Math.sin(boss.age)*.035);}if(boss.hit>0){ctx.strokeStyle='#fff5d0';ctx.lineWidth=2;ctx.beginPath();ctx.arc(boss.x,boss.y,60,0,TAU);ctx.stroke();}}
 ctx.lineCap='round';for(const s of shots){ctx.strokeStyle='#e4ffff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x-s.vx*.025,s.y+16);ctx.stroke();ctx.strokeStyle='#48d5ed';ctx.lineWidth=6;ctx.globalAlpha=.3;ctx.stroke();ctx.globalAlpha=1;}
 for(const b of bullets){const im=bulletImg(b.r);ctx.drawImage(im,b.x-im.half,b.y-im.half,im.half*2,im.half*2);}
 for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.r*2,p.r);}ctx.globalAlpha=1;
 ctx.save();ctx.globalCompositeOperation='lighter';for(const f of fxBursts){const im=extra['fx'+f.idx],u=f.t/f.dur,sc=(.35+u*.9)*(38+f.size*30)/im.height*2,w=im.width*sc,h=im.height*sc;ctx.globalAlpha=Math.max(0,1-u*u);ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.rot);ctx.drawImage(im,-w/2,-h/2,w,h);ctx.restore();}ctx.restore();ctx.globalAlpha=1;
 for(const r of rings){ctx.globalAlpha=r.life/.55;ctx.strokeStyle=r.color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,TAU);ctx.stroke();}ctx.globalAlpha=1;
 if(player.hp>0){const grow=drive>0?1+Math.sin(Math.min(1,(4.5-drive)*2)*Math.PI/2)*.85:1;ctx.fillStyle=drive>0?'#ff9b47':'#52eaff';ctx.globalAlpha=.7;ctx.beginPath();ctx.moveTo(player.x-6*grow,player.y+25*grow);ctx.lineTo(player.x,player.y+(40+Math.sin(t*40)*5)*grow);ctx.lineTo(player.x+6*grow,player.y+25*grow);ctx.fill();ctx.globalAlpha=1;sprite('soju',player.x,player.y,48*grow,65*grow,0,player.inv>0?.72:1);if(player.inv>0||drive>0){ctx.strokeStyle=drive>0?'#ffff85':'#66e7ff';ctx.globalAlpha=.5;ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(player.x,player.y,25*grow,0,TAU);ctx.stroke();ctx.globalAlpha=1;}ctx.fillStyle='#091b2c';ctx.beginPath();ctx.arc(player.x,player.y,5,0,TAU);ctx.fill();ctx.fillStyle='#6df9ff';ctx.beginPath();ctx.arc(player.x,player.y,2.5,0,TAU);ctx.fill();}
 if(transition>0){const tx=clamp((3.8-transition)*2,0,1);ctx.save();ctx.translate((1-tx)*W,0);for(let i=0;i<3;i++){ctx.fillStyle='#1e132cdd';ctx.strokeStyle=['#dfff42','#ff6d62','#cf8eff'][i];ctx.lineWidth=2;ctx.fillRect(50,275+i*53,380,43);ctx.strokeRect(50,275+i*53,380,43);ctx.fillStyle=ctx.strokeStyle;ctx.font='bold 14px monospace';ctx.fillText(i===0?'TRANSMISSION CLEARED':i===1?`NRK  /  ${String(score).padStart(6,'0')}`:'NEXT FREQUENCY →',67,302+i*53);}ctx.restore();}
 }for(const c of callouts){ctx.save();ctx.globalAlpha=Math.min(1,c.life*3);ctx.font='bold 11px monospace';ctx.textAlign='center';ctx.lineWidth=4;ctx.strokeStyle='#07101d';const x=clamp(c.x,85,W-85);ctx.strokeText(c.text,x,c.y);ctx.fillStyle=c.color;ctx.fillText(c.text,x,c.y);ctx.restore();}if(damageFlash>0){ctx.strokeStyle='#ff536b';ctx.lineWidth=10;ctx.globalAlpha=saved.reduced?.35:damageFlash*2;ctx.strokeRect(5,5,W-10,H-10);}if(flash>0){ctx.globalAlpha=Math.min(1,flash)*(saved.reduced?.35:.8);ctx.fillStyle='#fff8dc';ctx.fillRect(0,0,W,H);ctx.globalAlpha=1;}ctx.fillStyle='#000';ctx.globalAlpha=saved.reduced?0:.035;for(let y=0;y<H;y+=4)ctx.fillRect(0,y,W,1);ctx.globalAlpha=1;ctx.restore();}
function hud(){$('score').textContent=String(score).padStart(6,'0');$('mult').textContent=1+Math.min(3,Math.floor(combo/12));$('lives').textContent=Array.from({length:3},(_,i)=>i<player.hp?'●':'○').join(' ');$('lives').setAttribute('aria-label',`${player.hp} shields remaining`);$('stage-name').textContent=`0${stage+1} / ${stages[stage].name}`;$('boss-hud').hidden=!boss;if(boss){$('boss-name').textContent=stages[stage].boss;$('boss-health').value=boss.hp/boss.max;}$('flight-status').textContent=drive>0?'OVERDRIVE ACTIVE':`TRANSMISSION 0${stage+1} / LIVE`;$('weapon-label').textContent=`FIREPOWER ${player.power}/5 · RANK ${1+Math.round(rank*8)} · AUTO FIRE`;$('charge-fill').style.width=`${drive>0?drive/4.5*100:charge}%`;const can=charge>=100&&drive<=0&&state==='playing'&&transition<=0;$('overdrive-btn').disabled=!can;$('overdrive-btn').classList.toggle('ready',can);$('bomb-btn').disabled=!(bombs>0&&state==='playing'&&transition<=0);$('bomb-label').textContent='×'+bombs;$('charge-label').textContent=drive>0?'SKY AT FULL VOLUME':can?'READY — PRESS X / TAP':`${Math.floor(charge)}% / CHARGING`;}
function frame(now){const elapsed=Math.min(.1,(now-last)/1000||0);last=now;if(!qaManual){if(state==='playing'||state==='title'){acc+=elapsed;let n=0;while(acc>=1/60&&n++<6){step(1/60);acc-=1/60;}}draw();}requestAnimationFrame(frame);}
function key(e,down){if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||$('settings').open||$('help').open)return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','a','s','d','Shift','x','z','b','p','Escape'].includes(k))e.preventDefault();if(down){if(!e.repeat){if(k==='p'||k==='Escape'){state==='playing'?pause():state==='paused'?resume():null;return;}if(k==='x')activateDrive();if(k==='z'||k==='b')bombNow();if((k==='Enter'||k===' ')&&state==='title'&&e.target===cv)start();}if(state==='playing')keys.add(k);}else keys.delete(k);}
addEventListener('keydown',e=>key(e,true));addEventListener('keyup',e=>key(e,false));
function point(e){const r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H};}
cv.addEventListener('pointerdown',e=>{if(state!=='playing'||pointer)return;e.preventDefault();unlockAudio();cv.focus({preventScroll:true});const p=point(e);pointer={id:e.pointerId,...p};try{cv.setPointerCapture(e.pointerId);}catch{pointer=null;}});
cv.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id||state!=='playing')return;const p=point(e);player.x=clamp(player.x+(p.x-pointer.x)*1.25,25,W-25);player.y=clamp(player.y+(p.y-pointer.y)*1.25,85,H-38);pointer={id:e.pointerId,...p};});
for(const ev of ['pointerup','pointercancel','lostpointercapture'])cv.addEventListener(ev,e=>{if(pointer?.id===e.pointerId)pointer=null;});
addEventListener('blur',()=>pause());document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
$('start-btn').onclick=start;$('retry-btn').onclick=start;$('resume-btn').onclick=resume;$('pause-btn').onclick=pause;$('overdrive-btn').onclick=activateDrive;$('bomb-btn').onclick=bombNow;$('quit-btn').onclick=()=>finish(false);$('menu-btn').onclick=title;$('save-btn').onclick=saveScore;
$('home-link').onclick=e=>{e.preventDefault();if(state==='playing')pause();else if(state!=='paused')title();};
function openDialog(id){pause();keys.clear();pointer=null;$(id).showModal();}
$('settings-btn').onclick=()=>openDialog('settings');$('how-btn').onclick=()=>openDialog('help');
const fullscreen=$('fullscreen-btn');
if(!document.fullscreenEnabled)fullscreen.hidden=true;
fullscreen.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{fullscreen.textContent='FULLSCREEN UNAVAILABLE';}};
document.addEventListener('fullscreenchange',()=>{fullscreen.textContent=document.fullscreenElement?'EXIT FULLSCREEN':'FULLSCREEN';});
for(const id of ['settings','help'])$(id).addEventListener('close',()=>{if(state==='paused')$('resume-btn').focus({preventScroll:true});else if(state==='title')$('start-btn').focus({preventScroll:true});});
$('sound').checked=!!saved.sound;$('reduced').checked=!!saved.reduced;$('difficulty').value=saved.difficulty;
$('sound').onchange=e=>{saved.sound=e.target.checked;persist();unlockAudio();};$('reduced').onchange=e=>{saved.reduced=e.target.checked;persist();};$('difficulty').onchange=e=>{saved.difficulty=e.target.value;persist();};
updateScores();requestAnimationFrame(frame);
// Opt-in local QA controls are absent from ordinary game sessions.
if(QA)window.__qa={bomb:bombNow,setBombs(v){bombs=v;hud();},positions:()=>({bl:bullets.map(b=>[b.x,b.y]),en:enemies.map(e=>[e.x,e.y]),bo:boss?[boss.x,boss.y]:null}),start, pause,resume,activateDrive,hit:()=>{player.inv=0;takeHit();},state:()=>({bombs,rank,state,stage,stageTime,score,kills,charge,drive,transition,player:{...player},boss:boss?{...boss}:null,enemies:enemies.length,bullets:bullets.length,particles:particles.length,shots:shots.length,totalSpawned,escaped,ready,storageOK}),advance(seconds){qaManual=true;for(let i=0;i<Math.round(seconds*60);i++)step(1/60);hud();draw();},manual(v){qaManual=v;last=performance.now();acc=0;},god(v){qaGod=v;},setPlayer(v){Object.assign(player,v);},charge(v){charge=v;hud();},setBossHP(v){if(boss)boss.hp=v;},clearEnemies(){for(const e of enemies)if(e.hp>0)destroyEnemy(e);},addDrop(type){drops.push({x:player.x,y:player.y,type,age:0});},bullet(){bullets.push({x:player.x,y:player.y,r:5,vx:0,vy:0,color:'#fff'});},draw,finish,stats:()=>({sprites:Object.keys(sprites),scores:saved.scores,settings:saved})};
})();
